### ISSUE TITLE
LibreOffice Math icon depicts database

### ISSUE THREAD

**Issue by Kport1** [Arcticons-Team/Arcticons-Linux#40]
The LibreOffice Math icon may be better used for LibreOffice Base.

Math:
![libreoffice-math](https://github.com/Arcticons-Team/Arcticons-Linux/assets/75142870/2faf15c5-a458-4a19-86fc-9fbf9926578c)

Base:
![libreoffice-base](https://github.com/Arcticons-Team/Arcticons-Linux/assets/75142870/a8c73ff0-0cb9-4ae1-a5cb-f35f09983484)

Icon in question:
![libreoffice_math](https://github.com/Arcticons-Team/Arcticons-Linux/assets/75142870/6ddadd93-79aa-4a46-acc8-aeab71c3df87)

**Comment by autinerd** [comment]
Thanks!
